/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PersonService } from "../person.service";
import { Public } from "../../decorators/public.decorator";
import { PersonCreateInput } from "./PersonCreateInput";
import { PersonWhereInput } from "./PersonWhereInput";
import { PersonWhereUniqueInput } from "./PersonWhereUniqueInput";
import { PersonFindManyArgs } from "./PersonFindManyArgs";
import { PersonUpdateInput } from "./PersonUpdateInput";
import { Person } from "./Person";
import { FilmFindManyArgs } from "../../film/base/FilmFindManyArgs";
import { Film } from "../../film/base/Film";
import { FilmWhereUniqueInput } from "../../film/base/FilmWhereUniqueInput";
import { RaceFindManyArgs } from "../../race/base/RaceFindManyArgs";
import { Race } from "../../race/base/Race";
import { RaceWhereUniqueInput } from "../../race/base/RaceWhereUniqueInput";
import { StarshipFindManyArgs } from "../../starship/base/StarshipFindManyArgs";
import { Starship } from "../../starship/base/Starship";
import { StarshipWhereUniqueInput } from "../../starship/base/StarshipWhereUniqueInput";
import { VehicleFindManyArgs } from "../../vehicle/base/VehicleFindManyArgs";
import { Vehicle } from "../../vehicle/base/Vehicle";
import { VehicleWhereUniqueInput } from "../../vehicle/base/VehicleWhereUniqueInput";

export class PersonControllerBase {
  constructor(protected readonly service: PersonService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Person })
  async create(@common.Body() data: PersonCreateInput): Promise<Person> {
    return await this.service.create({
      data: {
        ...data,

        planet: data.planet
          ? {
              connect: data.planet,
            }
          : undefined,
      },
      select: {
        birthYear: true,
        createdAt: true,
        description: true,
        eyeColor: true,
        gender: true,
        hairColor: true,
        height: true,
        id: true,
        mass: true,
        name: true,

        planet: {
          select: {
            id: true,
          },
        },

        skinColor: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [Person] })
  @ApiNestedQuery(PersonFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Person[]> {
    const args = plainToClass(PersonFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        birthYear: true,
        createdAt: true,
        description: true,
        eyeColor: true,
        gender: true,
        hairColor: true,
        height: true,
        id: true,
        mass: true,
        name: true,

        planet: {
          select: {
            id: true,
          },
        },

        skinColor: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Person })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: PersonWhereUniqueInput
  ): Promise<Person | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        birthYear: true,
        createdAt: true,
        description: true,
        eyeColor: true,
        gender: true,
        hairColor: true,
        height: true,
        id: true,
        mass: true,
        name: true,

        planet: {
          select: {
            id: true,
          },
        },

        skinColor: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Person })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() data: PersonUpdateInput
  ): Promise<Person | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          planet: data.planet
            ? {
                connect: data.planet,
              }
            : undefined,
        },
        select: {
          birthYear: true,
          createdAt: true,
          description: true,
          eyeColor: true,
          gender: true,
          hairColor: true,
          height: true,
          id: true,
          mass: true,
          name: true,

          planet: {
            select: {
              id: true,
            },
          },

          skinColor: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Person })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: PersonWhereUniqueInput
  ): Promise<Person | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          birthYear: true,
          createdAt: true,
          description: true,
          eyeColor: true,
          gender: true,
          hairColor: true,
          height: true,
          id: true,
          mass: true,
          name: true,

          planet: {
            select: {
              id: true,
            },
          },

          skinColor: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @common.Get("/:id/films")
  @ApiNestedQuery(FilmFindManyArgs)
  async findManyFilms(
    @common.Req() request: Request,
    @common.Param() params: PersonWhereUniqueInput
  ): Promise<Film[]> {
    const query = plainToClass(FilmFindManyArgs, request.query);
    const results = await this.service.findFilms(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        director: true,
        episodeId: true,
        id: true,
        openingCrawl: true,
        producers: true,
        releaseDate: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/films")
  async connectFilms(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: FilmWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      films: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/films")
  async updateFilms(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: FilmWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      films: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/films")
  async disconnectFilms(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: FilmWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      films: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @Public()
  @common.Get("/:id/races")
  @ApiNestedQuery(RaceFindManyArgs)
  async findManyRaces(
    @common.Req() request: Request,
    @common.Param() params: PersonWhereUniqueInput
  ): Promise<Race[]> {
    const query = plainToClass(RaceFindManyArgs, request.query);
    const results = await this.service.findRaces(params.id, {
      ...query,
      select: {
        averageHeight: true,
        averageLifespan: true,
        classification: true,
        createdAt: true,
        description: true,
        designation: true,
        eyeColors: true,
        hairColors: true,
        id: true,
        language: true,
        name: true,
        skinColors: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/races")
  async connectRaces(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: RaceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      races: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/races")
  async updateRaces(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: RaceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      races: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/races")
  async disconnectRaces(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: RaceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      races: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @Public()
  @common.Get("/:id/starships")
  @ApiNestedQuery(StarshipFindManyArgs)
  async findManyStarships(
    @common.Req() request: Request,
    @common.Param() params: PersonWhereUniqueInput
  ): Promise<Starship[]> {
    const query = plainToClass(StarshipFindManyArgs, request.query);
    const results = await this.service.findStarships(params.id, {
      ...query,
      select: {
        cargoCapacity: true,
        consumables: true,
        costInCredits: true,
        createdAt: true,
        crew: true,
        description: true,
        hyperdriveRating: true,
        id: true,
        length: true,
        manufacturer: true,
        maxAtmospheringSpeed: true,
        mglt: true,
        model: true,
        name: true,
        passengers: true,
        starshipClass: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/starships")
  async connectStarships(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: StarshipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      starships: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/starships")
  async updateStarships(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: StarshipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      starships: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/starships")
  async disconnectStarships(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: StarshipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      starships: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @Public()
  @common.Get("/:id/vehicles")
  @ApiNestedQuery(VehicleFindManyArgs)
  async findManyVehicles(
    @common.Req() request: Request,
    @common.Param() params: PersonWhereUniqueInput
  ): Promise<Vehicle[]> {
    const query = plainToClass(VehicleFindManyArgs, request.query);
    const results = await this.service.findVehicles(params.id, {
      ...query,
      select: {
        cargoCapacity: true,
        consumables: true,
        costInCredits: true,
        createdAt: true,
        crew: true,
        description: true,
        id: true,
        length: true,
        manufacturer: true,
        maxAtmospheringSpeed: true,
        model: true,
        name: true,
        passengers: true,
        updatedAt: true,
        vehicleClass: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/vehicles")
  async connectVehicles(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: VehicleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vehicles: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/vehicles")
  async updateVehicles(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: VehicleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vehicles: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/vehicles")
  async disconnectVehicles(
    @common.Param() params: PersonWhereUniqueInput,
    @common.Body() body: VehicleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vehicles: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
