/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Public } from "../../decorators/public.decorator";
import { CreatePersonArgs } from "./CreatePersonArgs";
import { UpdatePersonArgs } from "./UpdatePersonArgs";
import { DeletePersonArgs } from "./DeletePersonArgs";
import { PersonFindManyArgs } from "./PersonFindManyArgs";
import { PersonFindUniqueArgs } from "./PersonFindUniqueArgs";
import { Person } from "./Person";
import { FilmFindManyArgs } from "../../film/base/FilmFindManyArgs";
import { Film } from "../../film/base/Film";
import { RaceFindManyArgs } from "../../race/base/RaceFindManyArgs";
import { Race } from "../../race/base/Race";
import { StarshipFindManyArgs } from "../../starship/base/StarshipFindManyArgs";
import { Starship } from "../../starship/base/Starship";
import { VehicleFindManyArgs } from "../../vehicle/base/VehicleFindManyArgs";
import { Vehicle } from "../../vehicle/base/Vehicle";
import { Planet } from "../../planet/base/Planet";
import { PersonService } from "../person.service";
@graphql.Resolver(() => Person)
export class PersonResolverBase {
  constructor(protected readonly service: PersonService) {}

  async _peopleMeta(
    @graphql.Args() args: PersonFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @Public()
  @graphql.Query(() => [Person])
  async people(@graphql.Args() args: PersonFindManyArgs): Promise<Person[]> {
    return this.service.findMany(args);
  }

  @Public()
  @graphql.Query(() => Person, { nullable: true })
  async person(
    @graphql.Args() args: PersonFindUniqueArgs
  ): Promise<Person | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Person)
  async createPerson(@graphql.Args() args: CreatePersonArgs): Promise<Person> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        planet: args.data.planet
          ? {
              connect: args.data.planet,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Person)
  async updatePerson(
    @graphql.Args() args: UpdatePersonArgs
  ): Promise<Person | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          planet: args.data.planet
            ? {
                connect: args.data.planet,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Person)
  async deletePerson(
    @graphql.Args() args: DeletePersonArgs
  ): Promise<Person | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @graphql.ResolveField(() => [Film])
  async films(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: FilmFindManyArgs
  ): Promise<Film[]> {
    const results = await this.service.findFilms(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @Public()
  @graphql.ResolveField(() => [Race])
  async races(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: RaceFindManyArgs
  ): Promise<Race[]> {
    const results = await this.service.findRaces(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @Public()
  @graphql.ResolveField(() => [Starship])
  async starships(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: StarshipFindManyArgs
  ): Promise<Starship[]> {
    const results = await this.service.findStarships(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @Public()
  @graphql.ResolveField(() => [Vehicle])
  async vehicles(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: VehicleFindManyArgs
  ): Promise<Vehicle[]> {
    const results = await this.service.findVehicles(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @Public()
  @graphql.ResolveField(() => Planet, { nullable: true })
  async planet(@graphql.Parent() parent: Person): Promise<Planet | null> {
    const result = await this.service.getPlanet(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
