/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsDate,
  ValidateNested,
  IsInt,
  IsNumber,
} from "class-validator";
import { Type } from "class-transformer";
import { Film } from "../../film/base/Film";
import { Planet } from "../../planet/base/Planet";
import { Race } from "../../race/base/Race";
import { Starship } from "../../starship/base/Starship";
import { Vehicle } from "../../vehicle/base/Vehicle";

@ObjectType()
class Person {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  birthYear!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  eyeColor!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Film],
  })
  @ValidateNested()
  @Type(() => Film)
  @IsOptional()
  films?: Array<Film>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  gender!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  hairColor!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  height!: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  mass!: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: () => Planet,
  })
  @ValidateNested()
  @Type(() => Planet)
  @IsOptional()
  planet?: Planet | null;

  @ApiProperty({
    required: false,
    type: () => [Race],
  })
  @ValidateNested()
  @Type(() => Race)
  @IsOptional()
  races?: Array<Race>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  skinColor!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Starship],
  })
  @ValidateNested()
  @Type(() => Starship)
  @IsOptional()
  starships?: Array<Starship>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [Vehicle],
  })
  @ValidateNested()
  @Type(() => Vehicle)
  @IsOptional()
  vehicles?: Array<Vehicle>;
}

export { Person as Person };
