/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Person,
  Film,
  Race,
  Starship,
  Vehicle,
  Planet,
} from "@prisma/client";

export class PersonServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.PersonFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonFindManyArgs>
  ): Promise<number> {
    return this.prisma.person.count(args);
  }

  async findMany<T extends Prisma.PersonFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonFindManyArgs>
  ): Promise<Person[]> {
    return this.prisma.person.findMany(args);
  }
  async findOne<T extends Prisma.PersonFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonFindUniqueArgs>
  ): Promise<Person | null> {
    return this.prisma.person.findUnique(args);
  }
  async create<T extends Prisma.PersonCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonCreateArgs>
  ): Promise<Person> {
    return this.prisma.person.create<T>(args);
  }
  async update<T extends Prisma.PersonUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonUpdateArgs>
  ): Promise<Person> {
    return this.prisma.person.update<T>(args);
  }
  async delete<T extends Prisma.PersonDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonDeleteArgs>
  ): Promise<Person> {
    return this.prisma.person.delete(args);
  }

  async findFilms(
    parentId: string,
    args: Prisma.FilmFindManyArgs
  ): Promise<Film[]> {
    return this.prisma.person
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .films(args);
  }

  async findRaces(
    parentId: string,
    args: Prisma.RaceFindManyArgs
  ): Promise<Race[]> {
    return this.prisma.person
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .races(args);
  }

  async findStarships(
    parentId: string,
    args: Prisma.StarshipFindManyArgs
  ): Promise<Starship[]> {
    return this.prisma.person
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .starships(args);
  }

  async findVehicles(
    parentId: string,
    args: Prisma.VehicleFindManyArgs
  ): Promise<Vehicle[]> {
    return this.prisma.person
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .vehicles(args);
  }

  async getPlanet(parentId: string): Promise<Planet | null> {
    return this.prisma.person
      .findUnique({
        where: { id: parentId },
      })
      .planet();
  }
}
