/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSONValue } from "@app/custom-validators";
import {
  IsOptional,
  IsString,
  IsInt,
  ValidateNested,
  IsNumber,
} from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { FilmCreateNestedManyWithoutPlanetsInput } from "./FilmCreateNestedManyWithoutPlanetsInput";
import { Type } from "class-transformer";
import { PersonCreateNestedManyWithoutPlanetsInput } from "./PersonCreateNestedManyWithoutPlanetsInput";

@InputType()
class PlanetCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  climates?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  diameter?: number | null;

  @ApiProperty({
    required: false,
    type: () => FilmCreateNestedManyWithoutPlanetsInput,
  })
  @ValidateNested()
  @Type(() => FilmCreateNestedManyWithoutPlanetsInput)
  @IsOptional()
  @Field(() => FilmCreateNestedManyWithoutPlanetsInput, {
    nullable: true,
  })
  films?: FilmCreateNestedManyWithoutPlanetsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  gravity?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  orbitalPeriod?: number | null;

  @ApiProperty({
    required: false,
    type: () => PersonCreateNestedManyWithoutPlanetsInput,
  })
  @ValidateNested()
  @Type(() => PersonCreateNestedManyWithoutPlanetsInput)
  @IsOptional()
  @Field(() => PersonCreateNestedManyWithoutPlanetsInput, {
    nullable: true,
  })
  people?: PersonCreateNestedManyWithoutPlanetsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  population?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rotationPeriod?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  surfaceWater?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  terrains?: InputJsonValue;
}

export { PlanetCreateInput as PlanetCreateInput };
