/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StarshipService } from "../starship.service";
import { Public } from "../../decorators/public.decorator";
import { StarshipCreateInput } from "./StarshipCreateInput";
import { StarshipWhereInput } from "./StarshipWhereInput";
import { StarshipWhereUniqueInput } from "./StarshipWhereUniqueInput";
import { StarshipFindManyArgs } from "./StarshipFindManyArgs";
import { StarshipUpdateInput } from "./StarshipUpdateInput";
import { Starship } from "./Starship";
import { FilmFindManyArgs } from "../../film/base/FilmFindManyArgs";
import { Film } from "../../film/base/Film";
import { FilmWhereUniqueInput } from "../../film/base/FilmWhereUniqueInput";
import { PersonFindManyArgs } from "../../person/base/PersonFindManyArgs";
import { Person } from "../../person/base/Person";
import { PersonWhereUniqueInput } from "../../person/base/PersonWhereUniqueInput";

export class StarshipControllerBase {
  constructor(protected readonly service: StarshipService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Starship })
  async create(@common.Body() data: StarshipCreateInput): Promise<Starship> {
    return await this.service.create({
      data: data,
      select: {
        cargoCapacity: true,
        consumables: true,
        costInCredits: true,
        createdAt: true,
        crew: true,
        description: true,
        hyperdriveRating: true,
        id: true,
        length: true,
        manufacturer: true,
        maxAtmospheringSpeed: true,
        mglt: true,
        model: true,
        name: true,
        passengers: true,
        starshipClass: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [Starship] })
  @ApiNestedQuery(StarshipFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Starship[]> {
    const args = plainToClass(StarshipFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        cargoCapacity: true,
        consumables: true,
        costInCredits: true,
        createdAt: true,
        crew: true,
        description: true,
        hyperdriveRating: true,
        id: true,
        length: true,
        manufacturer: true,
        maxAtmospheringSpeed: true,
        mglt: true,
        model: true,
        name: true,
        passengers: true,
        starshipClass: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Starship })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: StarshipWhereUniqueInput
  ): Promise<Starship | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        cargoCapacity: true,
        consumables: true,
        costInCredits: true,
        createdAt: true,
        crew: true,
        description: true,
        hyperdriveRating: true,
        id: true,
        length: true,
        manufacturer: true,
        maxAtmospheringSpeed: true,
        mglt: true,
        model: true,
        name: true,
        passengers: true,
        starshipClass: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Starship })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: StarshipWhereUniqueInput,
    @common.Body() data: StarshipUpdateInput
  ): Promise<Starship | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          cargoCapacity: true,
          consumables: true,
          costInCredits: true,
          createdAt: true,
          crew: true,
          description: true,
          hyperdriveRating: true,
          id: true,
          length: true,
          manufacturer: true,
          maxAtmospheringSpeed: true,
          mglt: true,
          model: true,
          name: true,
          passengers: true,
          starshipClass: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Starship })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: StarshipWhereUniqueInput
  ): Promise<Starship | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          cargoCapacity: true,
          consumables: true,
          costInCredits: true,
          createdAt: true,
          crew: true,
          description: true,
          hyperdriveRating: true,
          id: true,
          length: true,
          manufacturer: true,
          maxAtmospheringSpeed: true,
          mglt: true,
          model: true,
          name: true,
          passengers: true,
          starshipClass: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @common.Get("/:id/films")
  @ApiNestedQuery(FilmFindManyArgs)
  async findManyFilms(
    @common.Req() request: Request,
    @common.Param() params: StarshipWhereUniqueInput
  ): Promise<Film[]> {
    const query = plainToClass(FilmFindManyArgs, request.query);
    const results = await this.service.findFilms(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        director: true,
        episodeId: true,
        id: true,
        openingCrawl: true,
        producers: true,
        releaseDate: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/films")
  async connectFilms(
    @common.Param() params: StarshipWhereUniqueInput,
    @common.Body() body: FilmWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      films: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/films")
  async updateFilms(
    @common.Param() params: StarshipWhereUniqueInput,
    @common.Body() body: FilmWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      films: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/films")
  async disconnectFilms(
    @common.Param() params: StarshipWhereUniqueInput,
    @common.Body() body: FilmWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      films: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @Public()
  @common.Get("/:id/person")
  @ApiNestedQuery(PersonFindManyArgs)
  async findManyPerson(
    @common.Req() request: Request,
    @common.Param() params: StarshipWhereUniqueInput
  ): Promise<Person[]> {
    const query = plainToClass(PersonFindManyArgs, request.query);
    const results = await this.service.findPerson(params.id, {
      ...query,
      select: {
        birthYear: true,
        createdAt: true,
        description: true,
        eyeColor: true,
        gender: true,
        hairColor: true,
        height: true,
        id: true,
        mass: true,
        name: true,

        planet: {
          select: {
            id: true,
          },
        },

        skinColor: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/person")
  async connectPerson(
    @common.Param() params: StarshipWhereUniqueInput,
    @common.Body() body: PersonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      person: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/person")
  async updatePerson(
    @common.Param() params: StarshipWhereUniqueInput,
    @common.Body() body: PersonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      person: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/person")
  async disconnectPerson(
    @common.Param() params: StarshipWhereUniqueInput,
    @common.Body() body: PersonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      person: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
