/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Public } from "../../decorators/public.decorator";
import { CreateRaceArgs } from "./CreateRaceArgs";
import { UpdateRaceArgs } from "./UpdateRaceArgs";
import { DeleteRaceArgs } from "./DeleteRaceArgs";
import { RaceFindManyArgs } from "./RaceFindManyArgs";
import { RaceFindUniqueArgs } from "./RaceFindUniqueArgs";
import { Race } from "./Race";
import { FilmFindManyArgs } from "../../film/base/FilmFindManyArgs";
import { Film } from "../../film/base/Film";
import { PersonFindManyArgs } from "../../person/base/PersonFindManyArgs";
import { Person } from "../../person/base/Person";
import { RaceService } from "../race.service";
@graphql.Resolver(() => Race)
export class RaceResolverBase {
  constructor(protected readonly service: RaceService) {}

  async _racesMeta(
    @graphql.Args() args: RaceFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @Public()
  @graphql.Query(() => [Race])
  async races(@graphql.Args() args: RaceFindManyArgs): Promise<Race[]> {
    return this.service.findMany(args);
  }

  @Public()
  @graphql.Query(() => Race, { nullable: true })
  async race(@graphql.Args() args: RaceFindUniqueArgs): Promise<Race | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Race)
  async createRace(@graphql.Args() args: CreateRaceArgs): Promise<Race> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Race)
  async updateRace(@graphql.Args() args: UpdateRaceArgs): Promise<Race | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Race)
  async deleteRace(@graphql.Args() args: DeleteRaceArgs): Promise<Race | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @graphql.ResolveField(() => [Film])
  async films(
    @graphql.Parent() parent: Race,
    @graphql.Args() args: FilmFindManyArgs
  ): Promise<Film[]> {
    const results = await this.service.findFilms(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @Public()
  @graphql.ResolveField(() => [Person])
  async person(
    @graphql.Parent() parent: Race,
    @graphql.Args() args: PersonFindManyArgs
  ): Promise<Person[]> {
    const results = await this.service.findPerson(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
