/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsInt,
  ValidateNested,
  IsDate,
} from "class-validator";
import { PersonCreateNestedManyWithoutFilmsInput } from "./PersonCreateNestedManyWithoutFilmsInput";
import { Type } from "class-transformer";
import { PlanetCreateNestedManyWithoutFilmsInput } from "./PlanetCreateNestedManyWithoutFilmsInput";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { RaceCreateNestedManyWithoutFilmsInput } from "./RaceCreateNestedManyWithoutFilmsInput";
import { StarshipCreateNestedManyWithoutFilmsInput } from "./StarshipCreateNestedManyWithoutFilmsInput";
import { VehicleCreateNestedManyWithoutFilmsInput } from "./VehicleCreateNestedManyWithoutFilmsInput";

@InputType()
class FilmCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  director?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  episodeId?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  openingCrawl?: string | null;

  @ApiProperty({
    required: false,
    type: () => PersonCreateNestedManyWithoutFilmsInput,
  })
  @ValidateNested()
  @Type(() => PersonCreateNestedManyWithoutFilmsInput)
  @IsOptional()
  @Field(() => PersonCreateNestedManyWithoutFilmsInput, {
    nullable: true,
  })
  person?: PersonCreateNestedManyWithoutFilmsInput;

  @ApiProperty({
    required: false,
    type: () => PlanetCreateNestedManyWithoutFilmsInput,
  })
  @ValidateNested()
  @Type(() => PlanetCreateNestedManyWithoutFilmsInput)
  @IsOptional()
  @Field(() => PlanetCreateNestedManyWithoutFilmsInput, {
    nullable: true,
  })
  planet?: PlanetCreateNestedManyWithoutFilmsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  producers?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => RaceCreateNestedManyWithoutFilmsInput,
  })
  @ValidateNested()
  @Type(() => RaceCreateNestedManyWithoutFilmsInput)
  @IsOptional()
  @Field(() => RaceCreateNestedManyWithoutFilmsInput, {
    nullable: true,
  })
  race?: RaceCreateNestedManyWithoutFilmsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  releaseDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => StarshipCreateNestedManyWithoutFilmsInput,
  })
  @ValidateNested()
  @Type(() => StarshipCreateNestedManyWithoutFilmsInput)
  @IsOptional()
  @Field(() => StarshipCreateNestedManyWithoutFilmsInput, {
    nullable: true,
  })
  starship?: StarshipCreateNestedManyWithoutFilmsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => VehicleCreateNestedManyWithoutFilmsInput,
  })
  @ValidateNested()
  @Type(() => VehicleCreateNestedManyWithoutFilmsInput)
  @IsOptional()
  @Field(() => VehicleCreateNestedManyWithoutFilmsInput, {
    nullable: true,
  })
  vehicle?: VehicleCreateNestedManyWithoutFilmsInput;
}

export { FilmCreateInput as FilmCreateInput };
