/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Public } from "../../decorators/public.decorator";
import { CreateFilmArgs } from "./CreateFilmArgs";
import { UpdateFilmArgs } from "./UpdateFilmArgs";
import { DeleteFilmArgs } from "./DeleteFilmArgs";
import { FilmFindManyArgs } from "./FilmFindManyArgs";
import { FilmFindUniqueArgs } from "./FilmFindUniqueArgs";
import { Film } from "./Film";
import { PersonFindManyArgs } from "../../person/base/PersonFindManyArgs";
import { Person } from "../../person/base/Person";
import { PlanetFindManyArgs } from "../../planet/base/PlanetFindManyArgs";
import { Planet } from "../../planet/base/Planet";
import { RaceFindManyArgs } from "../../race/base/RaceFindManyArgs";
import { Race } from "../../race/base/Race";
import { StarshipFindManyArgs } from "../../starship/base/StarshipFindManyArgs";
import { Starship } from "../../starship/base/Starship";
import { VehicleFindManyArgs } from "../../vehicle/base/VehicleFindManyArgs";
import { Vehicle } from "../../vehicle/base/Vehicle";
import { FilmService } from "../film.service";
@graphql.Resolver(() => Film)
export class FilmResolverBase {
  constructor(protected readonly service: FilmService) {}

  async _filmsMeta(
    @graphql.Args() args: FilmFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @Public()
  @graphql.Query(() => [Film])
  async films(@graphql.Args() args: FilmFindManyArgs): Promise<Film[]> {
    return this.service.findMany(args);
  }

  @Public()
  @graphql.Query(() => Film, { nullable: true })
  async film(@graphql.Args() args: FilmFindUniqueArgs): Promise<Film | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Film)
  async createFilm(@graphql.Args() args: CreateFilmArgs): Promise<Film> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Film)
  async updateFilm(@graphql.Args() args: UpdateFilmArgs): Promise<Film | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Film)
  async deleteFilm(@graphql.Args() args: DeleteFilmArgs): Promise<Film | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @graphql.ResolveField(() => [Person])
  async person(
    @graphql.Parent() parent: Film,
    @graphql.Args() args: PersonFindManyArgs
  ): Promise<Person[]> {
    const results = await this.service.findPerson(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @Public()
  @graphql.ResolveField(() => [Planet])
  async planet(
    @graphql.Parent() parent: Film,
    @graphql.Args() args: PlanetFindManyArgs
  ): Promise<Planet[]> {
    const results = await this.service.findPlanet(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @Public()
  @graphql.ResolveField(() => [Race])
  async race(
    @graphql.Parent() parent: Film,
    @graphql.Args() args: RaceFindManyArgs
  ): Promise<Race[]> {
    const results = await this.service.findRace(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @Public()
  @graphql.ResolveField(() => [Starship])
  async starship(
    @graphql.Parent() parent: Film,
    @graphql.Args() args: StarshipFindManyArgs
  ): Promise<Starship[]> {
    const results = await this.service.findStarship(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @Public()
  @graphql.ResolveField(() => [Vehicle])
  async vehicle(
    @graphql.Parent() parent: Film,
    @graphql.Args() args: VehicleFindManyArgs
  ): Promise<Vehicle[]> {
    const results = await this.service.findVehicle(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
