/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TypingService } from "../typing.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Public } from "../../decorators/public.decorator";
import { TypingCreateInput } from "./TypingCreateInput";
import { TypingWhereInput } from "./TypingWhereInput";
import { TypingWhereUniqueInput } from "./TypingWhereUniqueInput";
import { TypingFindManyArgs } from "./TypingFindManyArgs";
import { TypingUpdateInput } from "./TypingUpdateInput";
import { Typing } from "./Typing";
import { MonsterFindManyArgs } from "../../monster/base/MonsterFindManyArgs";
import { Monster } from "../../monster/base/Monster";
import { MonsterWhereUniqueInput } from "../../monster/base/MonsterWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TypingControllerBase {
  constructor(
    protected readonly service: TypingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Typing",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Typing })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: TypingCreateInput): Promise<Typing> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [Typing] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(TypingFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Typing[]> {
    const args = plainToClass(TypingFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Typing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: TypingWhereUniqueInput
  ): Promise<Typing | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Typing",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Typing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: TypingWhereUniqueInput,
    @common.Body() data: TypingUpdateInput
  ): Promise<Typing | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Typing",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Typing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: TypingWhereUniqueInput
  ): Promise<Typing | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @common.Get("/:id/monsters")
  @ApiNestedQuery(MonsterFindManyArgs)
  async findManyMonsters(
    @common.Req() request: Request,
    @common.Param() params: TypingWhereUniqueInput
  ): Promise<Monster[]> {
    const query = plainToClass(MonsterFindManyArgs, request.query);
    const results = await this.service.findMonsters(params.id, {
      ...query,
      select: {
        biology: true,
        createdAt: true,
        dexNumber: true,

        generation: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        name: true,
        updatedAt: true,
        url: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Typing",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/monsters")
  async connectMonsters(
    @common.Param() params: TypingWhereUniqueInput,
    @common.Body() body: MonsterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      monsters: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Typing",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/monsters")
  async updateMonsters(
    @common.Param() params: TypingWhereUniqueInput,
    @common.Body() body: MonsterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      monsters: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Typing",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/monsters")
  async disconnectMonsters(
    @common.Param() params: TypingWhereUniqueInput,
    @common.Body() body: MonsterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      monsters: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
